<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

abstract class ItemPosition
{
        const ACCESSORY_POSITION_HAT = 6;
        const ACCESSORY_POSITION_CAPE = 7;
        const ACCESSORY_POSITION_BELT = 3;
        const ACCESSORY_POSITION_BOOTS = 5;
        const ACCESSORY_POSITION_AMULET = 0;
        const ACCESSORY_POSITION_SHIELD = 15;
        const ACCESSORY_POSITION_WEAPON = 1;
        const ACCESSORY_POSITION_PETS = 8;
        const ACCESSORY_POSITION_RIDE_HARNESS = 29;
        const INVENTORY_POSITION_RING_LEFT = 2;
        const INVENTORY_POSITION_RING_RIGHT = 4;
        const INVENTORY_POSITION_DOFUS_1 = 9;
        const INVENTORY_POSITION_DOFUS_2 = 10;
        const INVENTORY_POSITION_DOFUS_3 = 11;
        const INVENTORY_POSITION_DOFUS_4 = 12;
        const INVENTORY_POSITION_DOFUS_5 = 13;
        const INVENTORY_POSITION_DOFUS_6 = 14;
        const INVENTORY_POSITION_MOUNT = 16;
        const INVENTORY_POSITION_MUTATION = 20;
        const INVENTORY_POSITION_BOOST_FOOD = 21;
        const INVENTORY_POSITION_FIRST_BONUS = 22;
        const INVENTORY_POSITION_SECOND_BONUS = 23;
        const INVENTORY_POSITION_FIRST_MALUS = 24;
        const INVENTORY_POSITION_SECOND_MALUS = 25;
        const INVENTORY_POSITION_ROLEPLAY_BUFFER = 26;
        const INVENTORY_POSITION_FOLLOWER = 27;
        const INVENTORY_POSITION_COMPANION = 28;
        const INVENTORY_POSITION_COSTUME = 30;
        const INVENTORY_POSITION_NOT_EQUIPED = 63;
}
